version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vintekit-frontend:${BUILD_NUMBER:-latest}
    container_name: vintekit-frontend
    ports:
      # Jenkins is on 8080, so use 9090 for the app
      - "9090:80"
